<div class="row" id="acerca">
	<div class="center-align">
		<img src="<?php echo $this->baseUrl(); ?>/images/logo-small.png" alt="Agenda" id="logo"/>
	</div>
	<div class="col s12 center-align">
		<p class="texto-acerca">Easy Contacts es una aplicación desarrollada como prueba técnica para <b>Interesse® Agente de Seguros y de Fianzas, S.A. de C.V.</b></p>
		<p class="texto-acerca"><b>Desarrollador: </b> Ingeniero René Daniel Galicia Vázquez (renedaniel191992@gmail.com)</p>
			<div class="col s12 center-align">
		      	<ul class="collection with-header">
		        	<li class="collection-header"><h4>Herramientas utilizadas</h4></li>
		        	<li class="collection-item"><div>Zend Framework Versión 1.12</div></li>
		        	<li class="collection-item"><div>jQuery</div></li>
		        	<li class="collection-item"><div>Materializecss</div></li>
		        	<li class="collection-item"><div>Stored Procedures</div></li>
		        	<li class="collection-item"><div>Transacciones</div></li>
		        	<li class="collection-item"><div>Ajax</div></li>
		        	<li class="collection-item"><div>JavaScript</div></li>
		        	<li class="collection-item"><div>HTML</div></li>
		        	<li class="collection-item"><div>CSS</div></li>
		        	<li class="collection-item"><div>PHP</div></li>
		        	<li class="collection-item"><div>MySQL</div></li>
		      	</ul>
	      </div>
	</div>
</div>