<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />  
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
      <link href="<?php echo $this->baseUrl(); ?>/favicon.ico" type="image/x-icon" rel="icon"/>
      <link href="<?php echo $this->baseUrl(); ?>/favicon.ico" type="image/x-icon" rel="shortcut icon"/>
      <!-- Hojas de estilo -->
      <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl(); ?>/css/materialize.min.css" />
      <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl(); ?>/css/font-awesome.min.css" />
      <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl(); ?>/css/style.css" />
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
      <!-- Librerias JS -->
      <script src="<?php echo $this->baseUrl(); ?>/js/jquery.min.js"></script>
      <script src="<?php echo $this->baseUrl(); ?>/js/materialize.min.js"></script>
      <script src="<?php echo $this->baseUrl(); ?>/js/init.js"></script>
      <!-- Título de la página -->
      <title><?php echo $this->escape($this->title);?> | Easy Contacts</title>
   </head>
   <body>
      <!-- Barra de navegación -->
      <?php 
         //Obtenemos el nombre de la acción y el controlador para asignar la clase active al botón del Menú
         $controlador = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
         $accion = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
      ?>
      <div class="navbar">
         <nav class="grey lighten-3" role="navigation" id="menuNavegacion">
            <div class="nav-wrapper container">
               <a id="logo-container" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>" class="brand-logo"><img src="<?php echo $this->baseUrl(); ?>/images/logo.png" alt="Agenda" id="logo"/></a>
               <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
               <!-- Menú para versión de PC -->
               <ul class="right hide-on-med-and-down">
                  <li><a class="waves-effect  btn <?php echo ($controlador == 'index' && $accion == 'index')?'active': ''?>" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">Inicio</a></li>
                  <li><a class="waves-effect  btn <?php echo ($controlador == 'index' && $accion == 'acerca')?'active': ''?>" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'acerca')) ?>">Acerca</a></li>
               </ul>
            </div>
         </nav>
      </div>
      <!-- Menú para versión responsiva -->
      <ul id="nav-mobile" class="side-nav">
          <li><a class="waves-effect  btn btnm <?php echo ($controlador == 'index' && $accion == 'index') ? 'active' : '' ?>" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">Inicio</a></li>
          <li><a class="waves-effect  btn btnm <?php echo ($controlador == 'index' && $accion == 'acerca') ? 'active' : '' ?>" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'acerca')) ?>">Acerca</a></li>
      </ul><!-- Termina Barra de navegación -->
      <!-- Contenido de las vistas -->
      <div class="row" id="contenidoLayout">
         <h3 class="titulo-seccion"><?php echo $this->escape($this->title); ?></h1>
         <?php echo $this->layout()->content; ?>
      </div><!-- Termina Contenido de las vistas -->
      <!-- Social -->
      <section id="lab_social_icon_footer">
         <div class="container">
            <div class="text-center center-block">
               <a href="#"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
               <a href="#"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
               <a href="#"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
               <a href="#"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
            </div>
         </div>
      </section><!-- Termina Social -->
      <!-- Footer -->
      <footer class="page-footer site-footer teal grey darken-3">
         <div class="footer-copyright">
            <div class="container">
               Made by <a class="brown-text text-lighten-3" href="#">René Daniel</a>
            </div>
         </div>
      </footer><!-- Termina Footer -->
      <a href="javascript:" id="return-to-top"><i class="fa fa-chevron-up"></i></a>
      <script type="text/javascript">
         // Activamos el botón para ir arriba
         $(window).scroll(function() {
             if ($(this).scrollTop() >= 50) {        
                 $('#return-to-top').fadeIn(200);    
             } else {
                 $('#return-to-top').fadeOut(200);   
             }
         });
         $('#return-to-top').click(function() {      
             $('body,html').animate({
                 scrollTop : 0                       
             }, 500);
         });
      </script>
   </body>
</html>